// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testMTodoTasks(t *testing.T) {
	t.Parallel()

	query := MTodoTasks()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testMTodoTasksDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTodoTask{}
	if err = randomize.Struct(seed, o, mTodoTaskDBTypes, true, mTodoTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MTodoTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMTodoTasksQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTodoTask{}
	if err = randomize.Struct(seed, o, mTodoTaskDBTypes, true, mTodoTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := MTodoTasks().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MTodoTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMTodoTasksSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTodoTask{}
	if err = randomize.Struct(seed, o, mTodoTaskDBTypes, true, mTodoTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MTodoTaskSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MTodoTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMTodoTasksExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTodoTask{}
	if err = randomize.Struct(seed, o, mTodoTaskDBTypes, true, mTodoTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := MTodoTaskExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if MTodoTask exists: %s", err)
	}
	if !e {
		t.Errorf("Expected MTodoTaskExists to return true, but got false.")
	}
}

func testMTodoTasksFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTodoTask{}
	if err = randomize.Struct(seed, o, mTodoTaskDBTypes, true, mTodoTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	mTodoTaskFound, err := FindMTodoTask(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if mTodoTaskFound == nil {
		t.Error("want a record, got nil")
	}
}

func testMTodoTasksBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTodoTask{}
	if err = randomize.Struct(seed, o, mTodoTaskDBTypes, true, mTodoTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = MTodoTasks().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testMTodoTasksOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTodoTask{}
	if err = randomize.Struct(seed, o, mTodoTaskDBTypes, true, mTodoTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := MTodoTasks().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testMTodoTasksAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	mTodoTaskOne := &MTodoTask{}
	mTodoTaskTwo := &MTodoTask{}
	if err = randomize.Struct(seed, mTodoTaskOne, mTodoTaskDBTypes, false, mTodoTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}
	if err = randomize.Struct(seed, mTodoTaskTwo, mTodoTaskDBTypes, false, mTodoTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = mTodoTaskOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = mTodoTaskTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MTodoTasks().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testMTodoTasksCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	mTodoTaskOne := &MTodoTask{}
	mTodoTaskTwo := &MTodoTask{}
	if err = randomize.Struct(seed, mTodoTaskOne, mTodoTaskDBTypes, false, mTodoTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}
	if err = randomize.Struct(seed, mTodoTaskTwo, mTodoTaskDBTypes, false, mTodoTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = mTodoTaskOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = mTodoTaskTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MTodoTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testMTodoTasksInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTodoTask{}
	if err = randomize.Struct(seed, o, mTodoTaskDBTypes, true, mTodoTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MTodoTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMTodoTasksInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTodoTask{}
	if err = randomize.Struct(seed, o, mTodoTaskDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(mTodoTaskColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := MTodoTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMTodoTasksReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTodoTask{}
	if err = randomize.Struct(seed, o, mTodoTaskDBTypes, true, mTodoTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMTodoTasksReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTodoTask{}
	if err = randomize.Struct(seed, o, mTodoTaskDBTypes, true, mTodoTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MTodoTaskSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMTodoTasksSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MTodoTask{}
	if err = randomize.Struct(seed, o, mTodoTaskDBTypes, true, mTodoTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MTodoTasks().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	mTodoTaskDBTypes = map[string]string{`ID`: `integer`, `Title`: `character varying`, `Contents`: `text`, `Assignee`: `character varying`, `Label`: `character varying`, `Status`: `character varying`, `StartDate`: `timestamp without time zone`, `EndDate`: `timestamp without time zone`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`}
	_                = bytes.MinRead
)

func testMTodoTasksUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(mTodoTaskPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(mTodoTaskAllColumns) == len(mTodoTaskPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MTodoTask{}
	if err = randomize.Struct(seed, o, mTodoTaskDBTypes, true, mTodoTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MTodoTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, mTodoTaskDBTypes, true, mTodoTaskPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testMTodoTasksSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(mTodoTaskAllColumns) == len(mTodoTaskPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MTodoTask{}
	if err = randomize.Struct(seed, o, mTodoTaskDBTypes, true, mTodoTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MTodoTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, mTodoTaskDBTypes, true, mTodoTaskPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(mTodoTaskAllColumns, mTodoTaskPrimaryKeyColumns) {
		fields = mTodoTaskAllColumns
	} else {
		fields = strmangle.SetComplement(
			mTodoTaskAllColumns,
			mTodoTaskPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := MTodoTaskSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testMTodoTasksUpsert(t *testing.T) {
	t.Parallel()

	if len(mTodoTaskAllColumns) == len(mTodoTaskPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := MTodoTask{}
	if err = randomize.Struct(seed, &o, mTodoTaskDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MTodoTask: %s", err)
	}

	count, err := MTodoTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, mTodoTaskDBTypes, false, mTodoTaskPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MTodoTask struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MTodoTask: %s", err)
	}

	count, err = MTodoTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
