swagger: "2.0"
info:
    title: Todoタスク管理サービス
    description: HTTP service for todo management
    version: ""
host: localhost:8088
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /add:
        post:
            tags:
                - todoservice
            summary: addTodoTask todoservice
            description: Todoタスクを追加する。
            operationId: todoservice#addTodoTask
            parameters:
                - name: AddTodoTaskRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TodoserviceAddTodoTaskRequestBody'
                    required:
                        - title
                        - status
                        - start_date
                        - end_date
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: boolean
            schemes:
                - http
    /todo/{id}:
        get:
            tags:
                - todoservice
            summary: GetTodoTask todoservice
            description: 指定したTodoタスクの詳細を取得する。
            operationId: todoservice#GetTodoTask
            parameters:
                - name: id
                  in: path
                  description: Todo task id
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TodoserviceGetTodoTaskResponseBody'
                        required:
                            - id
                            - title
                            - status
            schemes:
                - http
        put:
            tags:
                - todoservice
            summary: UpdateTodoTask todoservice
            description: 指定したTodoタスクを更新する。
            operationId: todoservice#UpdateTodoTask
            parameters:
                - name: id
                  in: path
                  description: Todo task id
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: boolean
            schemes:
                - http
        delete:
            tags:
                - todoservice
            summary: DeleteTodoTask todoservice
            description: 指定したTodoタスクを削除する。
            operationId: todoservice#DeleteTodoTask
            parameters:
                - name: id
                  in: path
                  description: Todo task id
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: boolean
            schemes:
                - http
    /todolist:
        get:
            tags:
                - todoservice
            summary: GetTodoTaskList todoservice
            description: Todoタスク一覧を取得する。
            operationId: todoservice#GetTodoTaskList
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/todoTaskTitleResponse'
            schemes:
                - http
definitions:
    TodoserviceAddTodoTaskRequestBody:
        title: TodoserviceAddTodoTaskRequestBody
        type: object
        properties:
            asignee:
                type: string
                description: タスクを割り当てられた人の名前
                example: Voluptas amet fugit.
            contents:
                type: string
                description: Todoタスクの説明
                example: Autem amet distinctio cum quia ipsam quibusdam.
            end_date:
                type: string
                description: Todoタスクの終了予定日
                example: "1970-07-26"
                format: date
            label:
                type: string
                description: Todoタスクのラベル
                example: Id doloribus dignissimos sit voluptatibus et minima.
            start_date:
                type: string
                description: Todoタスクの開始予定日
                example: "1989-08-05"
                format: date
            status:
                type: string
                description: Todoタスクの進捗状況
                example: Quod sed.
            title:
                type: string
                description: Todoタスクのタイトル
                example: Eum exercitationem ut sunt et.
        example:
            asignee: Ea et id.
            contents: Dolores eos doloremque distinctio voluptates.
            end_date: "2011-07-04"
            label: Et atque recusandae esse.
            start_date: "2002-07-18"
            status: Eum atque repellendus.
            title: Ea commodi est explicabo dolorem corporis enim.
        required:
            - title
            - status
            - start_date
            - end_date
    TodoserviceGetTodoTaskResponseBody:
        title: TodoserviceGetTodoTaskResponseBody
        type: object
        properties:
            asignee:
                type: string
                description: タスクを割り当てられた人の名前
                example: Voluptatem autem.
            contents:
                type: string
                description: Todoタスクの説明
                example: Quasi est possimus perspiciatis dolores.
            end_date:
                type: string
                description: Todoタスクの終了予定日
                example: "2015-02-24"
                format: date
            id:
                type: integer
                description: TodoタスクのユニークID
                example: 7746551150572581924
                format: int64
            label:
                type: string
                description: Todoタスクのラベル
                example: Quis quia vitae quia quos ab.
            start_date:
                type: string
                description: Todoタスクの開始予定日
                example: "1985-11-24"
                format: date
            status:
                type: string
                description: Todoタスクの進捗状況
                example: Cumque odit.
            title:
                type: string
                description: Todoタスクのタイトル
                example: Quo enim consequatur.
        description: Todo task
        example:
            asignee: Suscipit error doloremque rerum numquam facere.
            contents: Tempore est consequuntur distinctio.
            end_date: "1983-11-11"
            id: 5396699997767219861
            label: Harum ipsam.
            start_date: "1992-10-19"
            status: Error ut dolorem eius.
            title: Incidunt molestiae exercitationem autem velit rerum.
        required:
            - id
            - title
            - status
    todoTaskTitleResponse:
        title: todoTaskTitleResponse
        type: object
        properties:
            id:
                type: integer
                description: TodoタスクのユニークID
                example: 1915472974225392669
                format: int64
            label:
                type: string
                description: Todoタスクのラベル
                example: Atque inventore dolores voluptatem.
            status:
                type: string
                description: Todoタスクの進捗状況
                example: Cumque maxime quo quod.
            title:
                type: string
                description: Todoタスクのタイトル
                example: Tenetur eaque itaque.
        description: Todoタスクの情報
        example:
            id: 3356894696563613590
            label: Ipsam non cumque.
            status: Quia nisi molestias.
            title: Corrupti laborum sed odio eos.
        required:
            - id
            - title
            - status
